version: '3'
services:
    web:
        build: ./docker/web
        restart: always
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - ./docker/db/data:/var/lib/mysql
        command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
