version: '3'
services:
    web:
        build: ./docker/web
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        build: ./docker/db
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_passwd
        volumes:
            - ./docker/db/data:/var/lib/mysql
        command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
